import {useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {SavedScan,CommitResult} from '../shared/types';
import {categories,categoryById} from '../shared/taxonomy';
import {CommitDialog} from './CommitDialog';
import {Select} from './Select';
import './styles.css';
const scan=JSON.parse(document.getElementById('report-data')!.textContent!) as SavedScan;
const repoName=(url:string)=>url.split('/').filter(Boolean).slice(-2).join('/');
function Report(){
  const [collapsed,setCollapsed]=useState(false),[filter,setFilter]=useState('all'),[category,setCategory]=useState('all'),[page,setPage]=useState(0),[selected,setSelected]=useState<CommitResult|null>(null);
  const threshold=scan.selection?.minProbability??scan.summary.options.threshold,progress=scan.summary.progress,options=scan.summary.options;
  const results=useMemo(()=>[...scan.results].filter(r=>(filter==='all'||filter==='bug'&&r.probabilities.bug_fix>=threshold||filter==='security'&&r.probabilities.security_fix>=threshold||filter==='context'&&r.probabilities.insufficient_context>=threshold)&&(category==='all'||r.categories.some(c=>c.id===category))).sort((a,b)=>(b.commit.committedAt??b.commit.date).localeCompare(a.commit.committedAt??a.commit.date)||b.commit.sha.localeCompare(a.commit.sha)),[filter,category,threshold]);
  const currentPage=Math.min(page,Math.max(0,Math.ceil(results.length/30)-1));
  function reset(){setFilter('all');setCategory('all');setPage(0);}
  return <div className={`app-shell ${collapsed?'collapsed':''}`}>
    {!collapsed&&<aside className="sidebar"><div className="brand"><span className="brand-mark">⎇</span><span>commit-miner</span><button className="icon" aria-label="Collapse sidebar" onClick={()=>setCollapsed(true)}>◧</button></div><nav aria-label="Report views">{[['all','All commits'],['security','Security fixes'],['bug','Bug fixes'],['context','Needs context']].map(([id,label])=><button key={id} aria-current={filter===id?'page':undefined} onClick={()=>{setFilter(id);setCategory('all');setPage(0);}}><span>{label}</span></button>)}</nav></aside>}
    <div className="content"><header className="topbar"><div>{collapsed&&<button className="icon" aria-label="Expand sidebar" onClick={()=>setCollapsed(false)}>◧</button>}<span>Commit history</span></div><div><button className="quiet" onClick={reset}>Reset filters</button></div></header>
    <main><div className="page-heading"><h1>{repoName(options.source)}</h1><p>{options.commit?`Commit ${options.commit}`:options.since||options.until?`${options.since??'Beginning'} → ${options.until??'Latest'}`:`Latest ${options.limit??250} commits`}{(options.since||options.until)&&options.limit?` · up to ${options.limit} commits`:''}</p></div>
    <section className="scan-progress" aria-label="Scan status"><div><span className="status-dot connected"/><strong>{scan.summary.status==='completed'?'Complete':scan.summary.status==='cancelled'?'Stopped':scan.summary.status==='running'?'In progress snapshot':'Incomplete'}</strong><span className="muted">{progress.done} / {progress.total} commits</span><div className="progress-actions"><time>{new Date(scan.summary.started).toLocaleString()}</time></div></div><div className="progress-track" role="progressbar" aria-label="Commit scan progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress.percent)}><span style={{width:`${progress.percent}%`}}/></div><div className="progress-meta"><span>{progress.classified} classified</span><span>{progress.bugs} bug fixes</span><span>{progress.security} security fixes</span><span>{progress.calls} calls · {progress.cached} cached</span><span>{progress.metadataOnly??0} metadata-only · {progress.failed??0} failed</span></div>{scan.error&&<p className="notice">{scan.error}</p>}</section>
    <section aria-label="Commit results"><div className="results-toolbar"><div className="tabs" aria-label="Commit filters">{[['all','All commits'],['security','Security'],['bug','Bugs'],['context','Needs context']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>{setFilter(id);setPage(0);}}>{label}</button>)}</div><Select label="Category" value={category} onChange={value=>{setCategory(value);setPage(0);}} options={[{value:'all',label:'All categories'},...(['security','bug','change'] as const).flatMap(family=>categories.filter(c=>c.family===family).map(c=>({value:c.id,label:c.label,detail:c.cwe?`CWE-${c.cwe}`:undefined,group:family==='security'?'Security / CWE':family==='bug'?'Bug fixes':'Change types'})))]}/></div>
    {scan.selection&&<p className="muted">Filtered · {scan.selection.matched} / {scan.selection.classified} classified</p>}
    <div className="commit-list">{results.slice(currentPage*30,(currentPage+1)*30).map(result=><button className="commit-row" key={result.commit.sha} aria-label={`Inspect commit ${result.commit.sha.slice(0,8)}`} onClick={()=>setSelected(result)}><span className="commit-dot"/><span className="commit-main"><strong>{result.commit.message.split('\n')[0]}</strong><span className="commit-meta">{result.commit.sha.slice(0,8)} · {result.commit.author} · {result.commit.date?new Date(result.commit.committedAt||result.commit.date).toLocaleDateString():'—'}{result.status==='partial'?' · Partial evidence':''}</span><span className="badges">{result.categories.slice(0,4).map(c=><span className={`badge ${categoryById[c.id]?.family??'change'}`} key={c.id}>{categoryById[c.id]?.cwe?`CWE-${categoryById[c.id].cwe} · `:''}{categoryById[c.id]?.label??c.id}</span>)}{result.categories.length>4&&<span className="more-labels">+{result.categories.length-4}</span>}{!result.categories.length&&<span className="muted">{result.status==='failed'?'Failed':result.status==='pending'?'Not analyzed':result.reviewCoverage==='metadata'?'Metadata review':'Unclassified'}</span>}</span></span><span className="commit-confidence"><strong>{result.status==='failed'||result.status==='pending'?'—':Math.round(100*Math.max(result.probabilities.security_fix??0,result.probabilities.bug_fix??0,...result.categories.map(c=>c.probability)))+'%'}</strong></span><span className="row-arrow">↗</span></button>)}</div>
    {!results.length&&<div className="empty"><span>⎇</span><h2>No commits</h2></div>}
    {results.length>30&&<div className="pagination"><button disabled={!currentPage} onClick={()=>setPage(currentPage-1)}>← Previous</button><span>{currentPage+1} / {Math.ceil(results.length/30)}</span><button disabled={(currentPage+1)*30>=results.length} onClick={()=>setPage(currentPage+1)}>Next →</button></div>}</section>
    </main></div>
    {selected&&<CommitDialog key={selected.commit.sha} result={selected} source={options.source} onClose={()=>setSelected(null)}/>}
  </div>;
}
createRoot(document.getElementById('root')!).render(<Report/>);
